### ISSUE TITLE
How to make named pipelines?

### ISSUE THREAD

**Issue by ivanpaulovich** [ivanpaulovich/FluentMediator#2]
I wish to Send or Publish to a named pipeline

**Comment by mikesol** [comment]
What would the use case be here? Would the name be passed as a third argument to the function with the signature `(handler, request)`?

**Comment by ivanpaulovich** [comment]
HI @mikesol,

The usage would be as a new argument for the `Send<T>()` and `Publish()` methods.

The current implementation uses a Dictionary of pipelines with the `Request Type` as Key, it would be nice that for every RequestType would exists a List of named Pipelines.

This changes would add fine grained control to the developer.

**Comment by mikesol** [comment]
Got it. Is the idea then to have some sort of pattern matching like redis, ie if you have `foo:bar` `foo:baz` and `bar:baz` and then send to `foo:*` it will pick up the channels with the right prefix?

**Comment by ivanpaulovich** [comment]
Yes, that would be great!

**Comment by ivanpaulovich** [comment]
Find in release v0.4.3
