### ISSUE TITLE
Support Scoped & Transient Lifetime

### ISSUE THREAD

**Issue by lilasquared** [ivanpaulovich/FluentMediator#31]
https://github.com/ivanpaulovich/FluentMediator/blob/f217ba01f4d5363641d62fbd487c95acddcaed65/src/FluentMediator.Microsoft.Extensions.DependencyInjection/FluentMediatorExtensions.cs#L12

This will likely cause issues with complex applications relying on container scope.  Would be nice to support different lifetimes.  Could maybe take inspiration from
https://github.com/jbogard/MediatR.Extensions.Microsoft.DependencyInjection

**Comment by ivanpaulovich** [comment]
Fixed on https://github.com/ivanpaulovich/FluentMediator/pull/43
