### ISSUE TITLE
Validate for Null Requests and throw strong typed exception

### ISSUE THREAD

**Issue by ivanpaulovich** [ivanpaulovich/FluentMediator#37]
Please failfast when the developer tries to publish/send null objects. The following code should be updated:

```c#
public async Task PublishAsync(object request)
{
// validate for null requests
    var pipeline = _pipelines.GetAsyncPipeline(request.GetType()); 
    await pipeline.PublishAsync(GetService, request!);
}        
```

**Comment by hadijahangiri** [comment]
May i start working on this?

**Comment by ivanpaulovich** [comment]
It would be nice @hadijahangiri :)

**Comment by hadijahangiri** [comment]
tnx

**Comment by ivanpaulovich** [comment]
Hey @hadijahangiri, I found the time to create PR which adds validation for null request. You may see the changes here https://github.com/ivanpaulovich/FluentMediator/commit/b3d03b1a75b8b603088dfb43cb6480b926b6012a

I wonder if you are interested in creating samples to showcase the project. What do you say?

**Comment by hadijahangiri** [comment]
sorry about my delay. very good.
I like to contribute in your project

**Comment by ivanpaulovich** [comment]
No problem! Take your time :)

What is more in need is a real sample application. There are good projects in GitHub using MediatR that I wish to implement using FluentMediator. Like the following:

https://github.com/miltoncamara/mediatr-netcore-sample

**Comment by hadijahangiri** [comment]
I try to use MediatR in one project

**Comment by ivanpaulovich** [comment]
The first "more complex" example of FluentMediator is available here https://github.com/ivanpaulovich/clean-architecture-manga
